Repository AntonioCarri11o/saec_backend, pull requests merged in 2025-03, with the labels that each got.

#6 feat. Authentication feature
  pom.xml
  src/main/java/com/saec/formtic/controller/auth/AuthController.java
  src/main/java/com/saec/formtic/controller/auth/authDTO/LoginDTO.java
  src/main/java/com/saec/formtic/repository/user/UserInfoRepository.java
  src/main/java/com/saec/formtic/security/jwt/JwtAuthFilter.java
  src/main/java/com/saec/formtic/security/service/JwtService.java
  src/main/java/com/saec/formtic/security/service/MainSecurity.java
  src/main/java/com/saec/formtic/security/service/UserDetailsServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#5 ADD:Implement mail service
  pom.xml
  src/main/java/com/saec/formtic/controller/exam/mail/MailController.java
  src/main/java/com/saec/formtic/controller/exam/mail/mailDTO/MailRequestDTO.java
  src/main/java/com/saec/formtic/model/mail/MailDesigns.java
  src/main/java/com/saec/formtic/service/mail/MailServise.java
  src/main/java/com/saec/formtic/utils/mail/MailConfiguration.java
  src/main/resources/application.properties
Labels: help wanted

#8 fix. hashing password
  src/main/java/com/saec/formtic/service/user/EmployeeService.java
Labels: bug
